### ISSUE TITLE
ALGO-61.1: Merge JEDI/UFS branches required for ufs-bundle into authoritative codebase

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#19]
## Description

PR #9 uses several branches instead of the authoritative code bases for both JEDI and UFS repos. We need to merge the following PRs into the authoritative code bases, which requires updating the JEDI components (issue #18) and the UFS components (reasonably up to date at the moment).

## Acceptance Criteria (Definition of Done)

The following UFS PRs need to be merged in addition to the linked PRs below (and they make up the 36 story points assigned to this issue directly):

- [x] ~~https://github.com/NOAA-EMC/AQM/pull/40 (estimate: 1 story point)~~ no longer needed, found workaround for case-sensitive filesystem on macOS with instructions
- [x] ~~https://github.com/NOAA-EMC/MOM6/pull/107 (estimate: 3 story points)~~ no longer needed, found workaround (using a patch for ufs-weather-model develop)
- [x] https://github.com/ufs-community/ccpp-physics/pull/41
    - This will get merged as part of https://github.com/ufs-community/ccpp-physics/pull/53, but until we update the ufs-weather-model used in ufs-bundle to a version that includes the change, we will have to entertain our own branch.
- n/a - https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/231. Closed this PR in favor of a different approach, see full description here: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/231#issuecomment-1441047312. For now, we will be using a branch called "feature/no_physics_dependencies_based_on_dev_emc" in the JCSDA fork of the GFDL_atmos_cubed_sphere dycore (https://github.com/jcsda/GFDL_atmos_cubed_sphere). This is meant to be a temporary solution until we have the required changes for compiling without CCPP from the dycore main branch merged into the dev/emc branch (estimate: 30 story points)
- [x] ~~https://github.com/NOAA-EMC/fv3atm/pull/620 (estimate: 1 story point)~~ according to @mark-a-potts no longer needed
- [x] ~~https://github.com/ufs-community/ufs-weather-model/pull/1504 (estimate: 1 story point)~~ no longer needed

**Comment by climbfuji** [comment]
Closing this issue depends on many external partners (EMC, GFDL, ...) and the timeline is unknown at this point.

**Comment by climbfuji** [comment]
@symoore90 @gibbsp This issue needs to become the new epic for AOP23 that deals with merging the ufs code changes into the various repositories at JCSDA and elsewhere.

**Comment by climbfuji** [comment]
We need to turn this into an epic and assign story points to the PRs listed above

**Comment by shlyaeva** [comment]
I agree with @climbfuji: this should be a different epic for the AOP23. I'm going to remove it as a sub-epic from ALGO-61, and the numbering of this epic should probably be elevated level up. Should it be in INFRA or ALGO? @climbfuji, @ytremolet, @symoore90, @gibbsp

**Comment by climbfuji** [comment]
You can keep it I don't want it ;-)

**Comment by shlyaeva** [comment]
Me neither 🤣

**Comment by climbfuji** [comment]
I removed the issues connected to this EPIC that weren't really tied to it. The last one left is to reenable using CRTM develop instead of the skylab-v7 tag. I believe I fixed that last week coincidentally in CRTM. Will check later today.

**Comment by climbfuji** [comment]
Closing this as completed. The last remaining issue (can't use CRTM develop, but tag v3.1.0-skylabv7) has been moved to AOP24.
